/**
 * Única ubicación del texto de interfaz redactado para la app
 * (botones, instrucciones de navegación y estados del sistema).
 * El contenido disciplinar vive en src/content/slides.json y proviene literalmente de los insumos.
 */
import type { Categoria, FaseLgr, PasoTrayecto } from '../content/types';

export const L = {
  app: {
    titulo: 'Los géneros periodísticos',
    marca: '“A Learning Lab” by Jesús Álvarez',
    lienzo: 'Presentación',
  },
  nav: {
    anterior: 'Pantalla anterior',
    siguiente: 'Pantalla siguiente',
    pantalla: (n: number, total: number) => `${n} / ${total}`,
    pantallaLarga: (n: number, total: number) => `Pantalla ${n} de ${total}`,
    ayuda:
      '→, Espacio o Av Pág: avanzar · ← o Re Pág: retroceder · Inicio/Fin: extremos · F: pantalla completa · N: notas · Esc: salir de un ejercicio',
  },
  fases: {
    yo: 'Yo hago',
    nosotros: 'Nosotros hacemos',
    ustedes: 'Ustedes hacen',
    tu: 'Tú haces',
    cierre: 'Cierre',
  } satisfies Record<FaseLgr, string>,
  pasos: {
    encuentra: 'Encuentra las pistas',
    explica: 'Explica su función',
    reconoce: 'Reconoce la intención',
    justifica: 'Justifica',
  } satisfies Record<PasoTrayecto, string>,
  pasosCortos: {
    encuentra: 'Encuentra',
    explica: 'Explica',
    reconoce: 'Reconoce',
    justifica: 'Justifica',
  } satisfies Record<PasoTrayecto, string>,
  categorias: {
    informativo: 'Informativo',
    interpretativo: 'Interpretativo',
    opinion: 'De opinión',
  } satisfies Record<Categoria, string>,
  formas: {
    informativo: 'círculo',
    interpretativo: 'cuadrado',
    opinion: 'triángulo',
  } satisfies Record<Categoria, string>,
  intenciones: {
    informar: 'Informar',
    explicar: 'Explicar',
    opinar: 'Opinar',
    hecho: 'Hecho',
  },
  visuales: {
    agregar: 'Agregar',
    causa: 'Causa',
    contraste: 'Contraste',
    aclarar: 'Aclarar',
    cerrar: 'Cerrar',
    fuente: 'Fuente',
    dato: 'Dato',
    valoracion: 'Valoración',
    autor: 'Autor',
    accion: 'Acción',
    ideaA: 'Idea',
    ideaB: 'Idea',
    antecedente: 'Antes',
    consecuencia: 'Efecto',
    contexto: 'Contexto',
    postura: 'Postura',
    razon: 'Razón',
    introduccion: 'Introducción',
    desarrollo: 'Desarrollo',
    conclusion: 'Conclusión',
    textoA: 'Texto A',
    textoB: 'Texto B',
    unaPista: '1 pista',
    variasPistas: 'Varias pistas',
    sinValoracion: 'Sin valoración',
    datos: 'Datos',
    perspectivas: 'Perspectivas',
    nosotros: 'Nosotros',
  },
  notas: {
    titulo: 'Notas del presentador',
    cerrar: 'Cerrar notas (N)',
    segmento: 'Segmento',
    fase: 'Fase',
    duracion: 'Duración prevista',
    sinDuracion: 'Sin duración en el guion',
    cronometro: 'Cronómetro del segmento',
    iniciar: 'Iniciar',
    pausar: 'Pausar',
    reiniciar: 'Reiniciar',
    guion: 'Guion',
    revisar: 'Para revisar',
    visual: 'Apoyo visual',
    segundos: (s: number) => `${s} s`,
    abrirPresentador: 'Abrir ventana del presentador (P)',
  },
  presentador: {
    titulo: 'Ventana del presentador',
    documento: 'Presentador · Los géneros periodísticos',
    actual: 'Pantalla actual',
    siguiente: 'Siguiente pantalla',
    fin: 'Fin de la presentación',
    anterior: 'Anterior',
    avanzar: 'Siguiente',
    sesion: 'Tiempo de la sesión',
    planeado: (min: number) => `de ${min} min previstos`,
    sincronizada: 'Sincronizada con la ventana proyectada',
    ayuda:
      'Proyecta la otra ventana. Aquí ves notas, cronómetros y la siguiente pantalla; ambas ventanas avanzan juntas. →/← o Espacio para navegar.',
    bloqueada:
      'El navegador bloqueó la ventana emergente: permite ventanas emergentes para este sitio y pulsa P de nuevo.',
  },
  glosario: {
    boton: 'Glosario',
    titulo: 'Glosario',
    cerrar: 'Cerrar glosario',
  },
  interaccion: {
    enviar: 'Enviar',
    otraRespuesta: 'Registrar otra respuesta',
    limpiar: 'Limpiar',
    seleccionaOpcion: 'Selecciona una opción para enviar.',
    completaHuecos: 'Coloca una expresión en cada espacio para enviar.',
    hueco: (n: number) => `Espacio ${n}`,
    huecoVacio: 'vacío',
    huecoCon: (n: number, v: string) => `Espacio ${n}: ${v}`,
    banco: 'Banco',
    instruccionArrastre:
      'Arrastra cada expresión a un espacio. Con teclado: enfoca una expresión, pulsa Espacio para tomarla, usa las flechas para elegir el espacio y Espacio para soltarla. También puedes pulsar una expresión y luego un espacio.',
    arrastreInicio: (v: string) => `Tomaste «${v}». Usa las flechas para elegir un espacio y Espacio para soltar.`,
    arrastreSobre: (v: string, destino: string) => `«${v}» sobre ${destino}.`,
    arrastreFin: (v: string, destino: string) => `«${v}» colocada en ${destino}.`,
    arrastreCancelado: (v: string) => `Se canceló el movimiento de «${v}».`,
    arrastreFuera: (v: string) => `«${v}» regresó al banco.`,
    seleccionada: 'seleccionada',
    evidencia: 'Evidencia seleccionada',
    evidenciaInstruccion: 'Selecciona dos expresiones del texto como evidencia.',
    registrada: (n: number) => `Respuesta ${n} registrada.`,
    participante: (n: number) => `Participante ${n}`,
    respuestasRegistradas: (n: number) => (n === 1 ? '1 respuesta registrada' : `${n} respuestas registradas`),
  },
  feedback: {
    correcto: 'Correcto',
    incorrecto: 'Revisa tu respuesta',
    sinClave: 'Respuesta registrada',
    sinClaveDetalle: 'Este reactivo no tiene respuesta correcta identificable.',
    esperada: (clave: string) => `Respuesta esperada: ${clave}`,
    aciertos: (a: number, t: number) => `${a} de ${t} espacios correctos`,
    justificacionSuficiente: 'Justificación suficiente: dos evidencias válidas',
    justificacionInsuficiente: 'Justificación insuficiente: faltan evidencias válidas',
  },
  qr: {
    titulo: 'Práctica independiente',
    instruccion: 'Escanea el código para abrir la ficha de práctica.',
    alt: 'Código QR que abre la ficha de práctica independiente en Google Drive',
    respaldo: 'Enlace de respaldo',
  },
  dashboard: {
    titulo: 'Resultados de la sesión',
    pestañas: {
      participacion: 'Participación',
      acierto: 'Acierto',
      confusion: 'Confusión',
      distractores: 'Distractores',
      sintesis: 'Síntesis',
    },
    simulado: 'Simulado',
    enVivo: 'En vivo',
    mostrarSimulado: 'Datos simulados',
    mostrarEnVivo: 'Datos en vivo',
    sinDatos: 'Aún no hay respuestas registradas.',
    sinSemilla:
      'Sin datos simulados: el guion no incluye banco de respuestas simuladas. Nivel de lectura y proceso PISA: sin etiqueta en el guion.',
    exportar: 'Exportar CSV',
    reiniciar: 'Reiniciar',
    confirmarReinicio: '¿Borrar todas las respuestas en vivo de esta sesión?',
    confirmar: 'Sí, borrar',
    cancelar: 'Cancelar',
    reiniciado: 'Se borraron las respuestas en vivo.',
    participacionPorReactivo: 'Respuestas por reactivo',
    aciertoPorReactivo: 'Acierto por reactivo',
    aciertoPorPaso: 'Acierto por paso del trayecto',
    aciertoPorNivel: 'Acierto por nivel de lectura',
    aciertoPorPisa: 'Acierto por proceso PISA',
    sinEtiqueta: 'Sin etiqueta',
    reactivo: 'Reactivo',
    distractorCorto: 'Opción incorrecta más elegida (veces)',
    soloCorrectas: 'Respuestas correctas en reactivos que piden justificación',
    suficiente: 'Suficiente',
    insuficiente: 'Insuficiente',
    matriz: 'Categoría correcta (filas) frente a categoría elegida (columnas)',
    correcta: 'Correcta',
    elegida: 'Elegida',
    distractor: 'Distractor más elegido',
    falla: 'Falla',
    sinFalla: 'El guion no indica la falla',
    ninguno: 'Sin errores',
    justificacion: 'Calidad de la justificación',
    tiempoMedio: 'Tiempo medio de respuesta',
    segundos: (s: number) => `${s.toFixed(1)} s`,
    sintesis: 'Síntesis pedagógica',
    pasoMayorFalla: 'Paso del trayecto con mayor falla',
    intervencion: 'Intervención que propone el guion',
    sinFallas: 'No hay respuestas incorrectas registradas.',
    porcentaje: (p: number) => `${Math.round(p)} %`,
    conteo: (n: number) => `${n}`,
    respuestas: (n: number) => (n === 1 ? '1 respuesta' : `${n} respuestas`),
    excluido: 'Sin clave: excluido del acierto',
  },
  sistema: {
    almacenamientoNoDisponible:
      'El almacenamiento local no está disponible; las respuestas se conservan solo mientras la página esté abierta.',
  },
} as const;
